// ═══════════════════════════════════════════════════════
// FARKLE FRENZY — CORE SACRED FILE
// This file implements game balance, scoring, or fairness logic.
// DO NOT MODIFY without:
//   1. Running all 16 farkleScorer test cases
//   2. Running npx tsc --noEmit (must show 0 errors)
//   3. Explicit developer approval
//   4. Updating DECISIONS_LOCKED_v4.txt if any constant changes
// See .ff-core-lock for full classification manifest.
// ═══════════════════════════════════════════════════════
//
// ADR-024/ADR-025 grid-native rewrite (GAP-1b/BUG-01 closure): this hook no
// longer drives chain-building/tap interaction from VoxelPhysicsSystem
// bodies. Multiplayer submits {row,col} positions via mpActions.submitChain
// and never resolves faces locally — the server (gameRoom.ts) is the sole
// source of scoring truth, using resolveChainFaces() against its own grid.
// Solo mode (no server to be authoritative over) uses a client-local
// SoloEngine instance running the *same* farkle-engine functions the server
// uses, and still commits through the existing sacred useFarkleStore exactly
// as before — only the chain's face SOURCE changed (grid cells, not
// physics-body faces), not the scoring/energy/bonus machinery itself.
//
// Known deferred items (flagged here, not silently dropped — see
// roadmap/01-current-sprint.md's P7 entry for full detail):
// - ice-thaw-on-adjacent-commit and lock-damage-on-column-commit are not
//   wired into the grid model yet (ICE/LOCK cells are permanently
//   unchainable until a follow-up pass adds this).
// - bomb/rainbow_bomb/mirror/ghost/catalyst/sphere/multiplier_orb are not
//   yet generated by the grid's spawn logic (createGrid/spawnTiles only
//   produce die/wild/stone/ice/lock today) — the type/resolution/handler
//   support for all 12 entities exists, but they won't appear in a live grid
//   until spawn-weight-driven generation is added.
// - RAINMAKER's face-targeted global bomb (skip radius, clear all dice of
//   one face board-wide) falls back to a normal radius-based detonation —
//   the sacred applyStandardBomb has no face-targeted mode.
// - Casino auto-chain (six-of-a-kind auto-play burst) is solo-only for now.
// - Bomb/explosion particle effects (explosionStore) are not wired — they
//   need real screen coordinates from the eventual PixiJS scene.

import { useCallback, useEffect, useRef, useState } from 'react';
import { buildScoreTable, lookupScore } from '@match3d/farkle-engine';
import { seededRng } from '@match3d/farkle-engine/csprng';
import { getNeighbors } from '@match3d/farkle-engine/gridUtils';
import type { Cell, DieFace, GridPos, LevelDef, GameMode } from '@match3d/farkle-shared';
import { CATALYST_WILD_BOOST, CATALYST_MAX_BOOST, GAME_CONSTANTS, HEIST_CONSTANTS } from '@match3d/farkle-shared';
import { useFarkleStore, MAX_CHAIN, WILD_PRIME_ENERGY, WILD_FRENZY_ENERGY } from '../store/farkleStore.js';
import { mpActions, useMultiplayerStore } from '../store/multiplayerStore.js';
import { SoloEngine } from '../game/soloEngine.js';

export const WIN_SCORE = 100_000;

// Module-level seeded RNG — replaces Math.random() for game events (W1 compliance).
// Seeded from 32 bits of crypto entropy so each session is unique.
const _sessionRng = seededRng(
  (crypto.getRandomValues(new Uint32Array(1))[0] ?? 0)
);

let _table: Int32Array | null = null;
function getTable(): Int32Array {
  if (!_table) _table = buildScoreTable();
  return _table;
}

function _currentGrid(isMultiplayer: boolean | undefined, engine: SoloEngine | null): Cell[][] | null {
  if (isMultiplayer) return useMultiplayerStore.getState().grid;
  return engine?.grid ?? null;
}

function _isChainableCell(cell: Cell): boolean {
  if (cell.state === 'WILD' || cell.state === 'MIRROR') return true;
  return (
    cell.face !== null &&
    cell.state === 'NORMAL' &&
    cell.type !== 'STONE' &&
    cell.type !== 'ICE' &&
    cell.type !== 'LOCK' &&
    cell.type !== 'BOMB_STANDARD' &&
    cell.type !== 'BOMB_RAINBOW' &&
    cell.type !== 'SPHERE' &&
    cell.type !== 'MULTIPLIER_ORB' &&
    cell.type !== 'NONE'
  );
}

function _rawFace(cell: Cell): number {
  return cell.state === 'WILD' ? 0 : (cell.face ?? 1);
}

export function useFarkleGame(
  levelDef?: LevelDef,
  gameMode?: GameMode,
  isMultiplayer?: boolean,
) {
  const store = useFarkleStore;
  const soloEngineRef = useRef<SoloEngine | null>(null);
  // Solo's grid lives on a plain ref (SoloEngine), not a reactive store — this
  // state exists purely to trigger a re-render with the fresh grid reference
  // whenever the engine mutates it, so callers (Board2DScene) can redraw.
  const [soloGrid, setSoloGrid] = useState<Cell[][] | null>(null);
  const mpGrid = useMultiplayerStore(s => s.grid);
  const grid = isMultiplayer ? mpGrid : soloGrid;
  const _bumpGrid = useCallback(() => setSoloGrid(soloEngineRef.current?.grid ?? null), []);
  const isDragging = useRef(false);
  const deadBoardAttemptsRef = useRef(0);
  const bankCountRef = useRef(0);
  const frenzyDoublerSpawnedRef = useRef(false);
  const casinoModeRef = useRef<number | null>(null);
  const casinoIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const effectiveWinScore = levelDef?.winScore ?? WIN_SCORE;
  const effectiveEnergyMult = levelDef?.energyMultiplier ?? 1.0;

  // ── Energy RAF tick — unchanged, purely store-driven ────────────────────────
  useEffect(() => {
    const lastTickRef = { current: performance.now() };
    const tick = (now: number) => {
      const deltaMs = now - lastTickRef.current;
      const elapsed = deltaMs / 1000;
      lastTickRef.current = now;
      const { mode, gamePhase, doublerCells } = store.getState();
      if (gamePhase === 'playing') {
        if (mode === 'PRIME') store.getState().addEnergy(5 * elapsed);
        else if (mode === 'FRENZY') {
          const { energy } = store.getState();
          const drainRate = energy < 75 ? 3 : 5;
          store.getState().addEnergy(-drainRate * elapsed);
          if (store.getState().energy <= 0 && store.getState().gamePhase === 'playing') {
            store.getState().bankScore();
            const { banked } = store.getState();
            store.setState({ gamePhase: banked >= effectiveWinScore ? 'win' : 'lose' });
          }
        }
        store.getState().tickDisruptCharge(deltaMs);
        store.getState().tickTimer(deltaMs);
        const heistState = store.getState();
        if (heistState.heistActive && heistState.heistExpiresAt !== null && now > heistState.heistExpiresAt) {
          store.getState().claimVault();
        }
        const rallyState = store.getState();
        if (rallyState.rallyDecisionActive && rallyState.rallyDecisionExpiresAt !== null && now > rallyState.rallyDecisionExpiresAt) {
          store.getState().bankScore();
          store.getState().setRallyDecision(false);
          if (store.getState().banked >= effectiveWinScore) store.setState({ gamePhase: 'win' });
        }
      }
      if (doublerCells.length > 0) {
        const alive = doublerCells.filter(d => d.expiresAt > now);
        if (alive.length !== doublerCells.length) {
          store.setState({ doublerCells: alive });
        }
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    const rafRef = { current: null as number | null };
    rafRef.current = requestAnimationFrame(tick);
    return () => { if (rafRef.current !== null) cancelAnimationFrame(rafRef.current); };
  }, []);

  // ── Doubler cell: spawn 2 random columns on first FRENZY entry ───────────────
  useEffect(() => {
    return store.subscribe(
      s => s.mode,
      (mode, prev) => {
        if (mode === 'FRENZY' && prev !== 'FRENZY' && !frenzyDoublerSpawnedRef.current) {
          frenzyDoublerSpawnedRef.current = true;
          if (!isMultiplayer) {
            const cols = _randomColumns(2);
            for (const col of cols) store.getState().spawnDoublerCell(col, 12_000);
          }
        }
      },
    );
  }, []);

  // ── Chain score sync (live preview while dragging) ──────────────────────────
  useEffect(() => {
    return store.subscribe(
      s => s.chainFaces,
      (faces) => {
        if (faces.length === 0) { store.setState({ chainScore: 0 }); return; }
        const resolved = _resolveChainFacesPreview(faces);
        const score = lookupScore(resolved as DieFace[], getTable());
        store.setState({ chainScore: score });
      },
    );
  }, []);

  // ── Chain drag API (grid-native: row/col, not bodyId) ───────────────────────

  const startChain = useCallback((row: number, col: number) => {
    const s = store.getState();
    if (s.gamePhase !== 'playing') return;
    const grid = _currentGrid(isMultiplayer, soloEngineRef.current);
    const cell = grid?.[row]?.[col];
    if (!cell || !_isChainableCell(cell)) return;
    // NORMAL mode: only face 1 or 5 can be selected (single-die tap-score only)
    if (s.mode === 'NORMAL' && cell.state !== 'WILD' && cell.state !== 'MIRROR' && cell.face !== 1 && cell.face !== 5) return;
    isDragging.current = true;
    store.getState().clearChain();
    store.getState().addToChain(`${row},${col}`, _rawFace(cell));
  }, [isMultiplayer]);

  const extendChain = useCallback((row: number, col: number) => {
    if (!isDragging.current) return;
    const s = store.getState();
    if (s.gamePhase !== 'playing') return;
    const grid = _currentGrid(isMultiplayer, soloEngineRef.current);
    const cell = grid?.[row]?.[col];
    if (!cell || !_isChainableCell(cell)) return;

    const { chain, mode } = s;
    if (mode === 'NORMAL') return;
    if (chain.length >= MAX_CHAIN) return;
    const id = `${row},${col}`;
    if (chain.length >= 2 && chain[chain.length - 2] === id) {
      store.getState().removeLastFromChain();
      return;
    }
    if (chain.includes(id)) return;

    const lastId = chain[chain.length - 1];
    if (lastId && grid) {
      const [lr, lc] = lastId.split(',').map(Number) as [number, number];
      const neighbors = getNeighbors(grid, lr, lc);
      if (!neighbors.some(n => n.row === row && n.col === col)) return;
    }
    store.getState().addToChain(id, _rawFace(cell));
  }, [isMultiplayer]);

  const endChain = useCallback(() => {
    if (!isDragging.current) return;
    isDragging.current = false;

    const s = store.getState();
    if (s.gamePhase !== 'playing' || s.chain.length === 0) {
      store.getState().clearChain();
      return;
    }

    const chainIds = [...s.chain];
    const chainPositions: GridPos[] = chainIds.map(id => {
      const [r, c] = id.split(',').map(Number) as [number, number];
      return { row: r, col: c };
    });

    if (isMultiplayer) {
      // Server-authoritative (GAP-1b/BUG-01 closed): submit positions only,
      // never faces. CHAIN_RESULT → syncFromServer updates the store when
      // the server replies; no local scoring here.
      store.getState().clearChain();
      mpActions.submitChain(chainPositions);
      return;
    }

    const engine = soloEngineRef.current;
    if (!engine) { store.getState().clearChain(); return; }

    const resolvedFaces = engine.resolveFaces(chainPositions);
    store.setState({ chainFaces: resolvedFaces });
    const result = store.getState().commitChain();

    if (result === 'ok') {
      const wildCount = chainPositions.filter(p => engine.grid[p.row]?.[p.col]?.state === 'WILD').length;
      if (wildCount > 0) {
        if (s.mode === 'PRIME') store.getState().addEnergy(wildCount * WILD_PRIME_ENERGY);
        else if (s.mode === 'FRENZY') store.getState().addEnergy(wildCount * WILD_FRENZY_ENERGY);
      }
    }

    if (s.multiplierOrbActive && result === 'ok') {
      store.setState(prev => ({
        banked: prev.banked + Math.round(prev.unbanked * 0.5),
        multiplierOrbActive: false,
      }));
    }

    if (result === 'ok') {
      const now = Date.now();
      const doublerCells = store.getState().doublerCells.filter(d => d.active && d.expiresAt > now);
      const chainColumns = new Set(chainPositions.map(p => p.col));
      for (const dc of doublerCells) {
        if (chainColumns.has(dc.column)) {
          const after = store.getState();
          const bankDelta = after.banked - s.banked;
          const unbankedDelta = after.unbanked - s.unbanked;
          store.setState(prev => ({
            banked: prev.banked + Math.max(0, bankDelta),
            unbanked: prev.unbanked + Math.max(0, unbankedDelta),
          }));
          store.getState().consumeDoublerCell(dc.column);
          break;
        }
      }
    }

    if (result === 'ok' && s.rallyRole === 'ARCHIVIST') {
      store.getState().drainFarklePool(GAME_CONSTANTS.ARCHIVIST_PCT);
    }

    if (result === 'ok' && (gameMode === 'HEIST_FREE' || gameMode === 'HEIST_CASINO')) {
      store.setState(prev => {
        const earned = prev.unbanked - s.unbanked;
        if (earned <= 0) return prev;
        const toVault = Math.round(earned * HEIST_CONSTANTS.VAULT_SPLIT);
        return { unbanked: prev.unbanked - toVault, vaultPts: prev.vaultPts + toVault };
      });
    }

    if (result === 'ok' && chainIds.length === MAX_CHAIN && (gameMode === 'RALLY_FREE' || gameMode === 'RALLY_CASINO')) {
      store.getState().setRallyDecision(true, Date.now() + 3000);
    }

    const hasCatalyst = chainPositions.some(p => engine.grid[p.row]?.[p.col]?.type === 'CATALYST');
    if (result === 'ok' && hasCatalyst) {
      store.setState(prev => ({
        catalystBoostPct: Math.min(prev.catalystBoostPct + CATALYST_WILD_BOOST, CATALYST_MAX_BOOST),
      }));
    }

    if (result === 'ok') {
      const faceCounts = resolvedFaces.reduce(
        (acc, f) => { acc[f] = (acc[f] ?? 0) + 1; return acc; },
        {} as Record<number, number>,
      );
      const maxCount = Math.max(0, ...Object.values(faceCounts));
      const isSixOfAKind = maxCount >= 6;
      if (isSixOfAKind) {
        if (casinoIntervalRef.current) clearInterval(casinoIntervalRef.current);
        casinoModeRef.current = Date.now() + 5000;
        casinoIntervalRef.current = setInterval(() => {
          if (!casinoModeRef.current || Date.now() >= casinoModeRef.current) {
            clearInterval(casinoIntervalRef.current!);
            casinoIntervalRef.current = null;
            casinoModeRef.current = null;
            return;
          }
          _doCasinoSoloChain(soloEngineRef.current, _bumpGrid);
        }, 900);
      }
      // Straight / five-equal-chain combo bomb spawns: deferred, see header note.
    }

    if (result === 'farkle') {
      store.getState().clearChain();
      setTimeout(_checkDeadBoard, 150);
      return;
    }

    engine.refillAfterChain(chainPositions, store.getState().catalystBoostPct);
    _bumpGrid();
    store.getState().clearChain();

    const { banked, unbanked } = store.getState();
    if (banked + unbanked + store.getState().pendingBombScore >= effectiveWinScore) {
      store.setState({ gamePhase: 'win' });
      return;
    }

    setTimeout(_checkDeadBoard, 150);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isMultiplayer, gameMode, effectiveWinScore, _bumpGrid]);

  // ── Tap handler: sphere, orb, ghost, bomb, rainbow bomb (grid row/col) ──────

  const tapEntity = useCallback((row: number, col: number) => {
    const s = store.getState();
    if (s.gamePhase !== 'playing') return;
    const grid = _currentGrid(isMultiplayer, soloEngineRef.current);
    const cell = grid?.[row]?.[col];
    if (!cell) return;

    if (isMultiplayer) {
      if (cell.type === 'SPHERE') { mpActions.tapSphere(row, col); return; }
      if (cell.type === 'MULTIPLIER_ORB') { mpActions.collectOrb(row, col); return; }
      if (cell.type === 'BOMB_STANDARD') {
        if (s.rallyRole === 'RAINMAKER') { store.getState().setPendingRainmakerBombId(`${row},${col}`); return; }
        mpActions.detonateBomb(row, col);
        return;
      }
      if (cell.type === 'BOMB_RAINBOW') { mpActions.detonateRainbowBomb(row, col); return; }
      if (cell.state === 'GHOST_PENDING') { mpActions.anchorGhost(row, col); return; }
      return;
    }

    const engine = soloEngineRef.current;
    if (!engine) return;

    if (cell.type === 'SPHERE') {
      const gained = engine.tapSphere(row, col);
      if (gained > 0) { store.getState().addEnergy(gained); _bumpGrid(); }
      return;
    }
    if (cell.type === 'MULTIPLIER_ORB') {
      if (engine.collectOrb(row, col)) { store.setState({ multiplierOrbActive: true }); _bumpGrid(); }
      return;
    }
    if (cell.type === 'BOMB_STANDARD') {
      if (s.rallyRole === 'RAINMAKER') { store.getState().setPendingRainmakerBombId(`${row},${col}`); return; }
      const pts = engine.detonateBomb(row, col);
      if (pts > 0) {
        store.setState(prev => ({ banked: prev.banked + pts, pendingBombScore: prev.pendingBombScore + pts }));
        _bumpGrid();
        if (store.getState().banked >= effectiveWinScore) store.setState({ gamePhase: 'win' });
      }
      return;
    }
    if (cell.type === 'BOMB_RAINBOW') {
      const pts = engine.detonateRainbowBomb(row, col);
      if (pts > 0) {
        store.setState(prev => ({ banked: prev.banked + pts }));
        _bumpGrid();
        if (store.getState().banked >= effectiveWinScore) store.setState({ gamePhase: 'win' });
      }
      return;
    }
    if (cell.state === 'GHOST_PENDING') {
      engine.anchorGhost(row, col);
      _bumpGrid();
    }
  }, [isMultiplayer, effectiveWinScore, _bumpGrid]);

  // Rally Pass: hold unbanked, reset chain. CONDUCTOR gets +1 multiplierStep (B6).
  const passScore = useCallback(() => {
    const s = store.getState();
    if (s.gamePhase !== 'playing') return;
    store.getState().passScore();
    if (s.rallyRole === 'CONDUCTOR') {
      store.setState(prev => ({ multiplierStep: Math.min(prev.multiplierStep + 1, 5) }));
    }
  }, []);

  const bankScore = useCallback(() => {
    const s = store.getState();
    if (s.gamePhase !== 'playing' || s.unbanked === 0) return;
    store.getState().bankScore();
    if (!isMultiplayer) {
      bankCountRef.current += 1;
      if (bankCountRef.current % 3 === 0) {
        const cols = _randomColumns(1);
        for (const col of cols) store.getState().spawnDoublerCell(col, 30_000);
      }
    }
    const { banked } = store.getState();
    if (banked >= effectiveWinScore) store.setState({ gamePhase: 'win' });
  }, [effectiveWinScore, isMultiplayer]);

  function _checkDeadBoard() {
    if (isMultiplayer) return; // server owns dead-board recovery for multiplayer
    const engine = soloEngineRef.current;
    if (!engine || !engine.isDeadBoard()) { deadBoardAttemptsRef.current = 0; return; }
    deadBoardAttemptsRef.current += 1;
    engine.reshuffleFaces();
    _bumpGrid();
    if (deadBoardAttemptsRef.current > 3) deadBoardAttemptsRef.current = 0;
  }

  const startGame = useCallback(() => {
    store.getState().resetGame();
    let timeRemaining: number | null = null;
    if (gameMode === 'HEIST_FREE' || gameMode === 'HEIST_CASINO') timeRemaining = 90;
    else if (gameMode === 'RALLY_FREE' || gameMode === 'RALLY_CASINO') timeRemaining = 180;
    else if (levelDef?.timeLimitSec) timeRemaining = levelDef.timeLimitSec;

    store.setState({
      gamePhase: 'playing', energy: 1 * effectiveEnergyMult, mode: 'PRIME',
      ...(timeRemaining !== null ? { timeRemaining } : {}),
    });
    deadBoardAttemptsRef.current = 0;
    bankCountRef.current = 0;
    frenzyDoublerSpawnedRef.current = false;
    if (!isMultiplayer) {
      soloEngineRef.current = new SoloEngine();
      setSoloGrid(soloEngineRef.current.grid);
    }
  }, [levelDef, effectiveEnergyMult, gameMode, isMultiplayer]);

  // RAINMAKER: called by FarkleHUD face picker with the chosen face (1-6).
  // NOTE: the sacred applyStandardBomb has no face-targeted global-clear
  // mode (unlike VoxelPhysicsSystem.activateBomb's old targetFace path) —
  // falls back to a normal radius-based detonation. Flagged, not silent.
  const confirmRainmakerBomb = useCallback((face: number) => {
    const s = store.getState();
    const bombId = s.pendingRainmakerBombId;
    if (!bombId) return;
    const [row, col] = bombId.split(',').map(Number) as [number, number];
    store.getState().setPendingRainmakerBombId(null);
    store.getState().setRainmakerBombFace(null);

    if (isMultiplayer) {
      mpActions.detonateBomb(row, col, face);
      return;
    }
    const engine = soloEngineRef.current;
    if (!engine) return;
    const pts = engine.detonateBomb(row, col);
    if (pts > 0) {
      store.setState(prev => ({ banked: prev.banked + pts, pendingBombScore: prev.pendingBombScore + pts }));
      _bumpGrid();
    }
    setTimeout(_checkDeadBoard, 150);
  }, [isMultiplayer, _bumpGrid]);

  // C1: Heist — initiate vault heist (costs HEIST_ENERGY_COST energy)
  const initiateHeist = useCallback(() => {
    const s = store.getState();
    if (s.gamePhase !== 'playing') return;
    if (s.heistActive) return;
    if (s.vaultPts < HEIST_CONSTANTS.VAULT_THRESHOLD) return;
    if (s.energy < HEIST_CONSTANTS.HEIST_ENERGY_COST) return;
    store.getState().addEnergy(-HEIST_CONSTANTS.HEIST_ENERGY_COST);
    store.getState().setHeistActive('local', Date.now() + HEIST_CONSTANTS.HEIST_WINDOW_MS);
  }, []);

  const blockHeist = useCallback(() => {
    const s = store.getState();
    if (!s.heistActive) return;
    store.getState().cancelHeist();
  }, []);

  const rallyBank = useCallback(() => {
    const s = store.getState();
    if (!s.rallyDecisionActive) return;
    store.getState().bankScore();
    store.getState().setRallyDecision(false);
    if (store.getState().banked >= effectiveWinScore) store.setState({ gamePhase: 'win' });
  }, [effectiveWinScore]);

  const rallyPass = useCallback(() => {
    const s = store.getState();
    if (!s.rallyDecisionActive) return;
    if (s.rallyRole === 'CONDUCTOR') {
      store.setState(prev => ({ multiplierStep: Math.min(prev.multiplierStep + 1, 5) }));
    }
    store.getState().passScore();
    store.getState().setRallyDecision(false);
  }, []);

  const rallyContinue = useCallback(() => {
    const s = store.getState();
    if (!s.rallyDecisionActive) return;
    store.getState().setRallyDecision(false);
  }, []);

  return {
    grid, startChain, extendChain, endChain, tapEntity, bankScore, passScore,
    startGame, confirmRainmakerBomb, initiateHeist, blockHeist,
    rallyBank, rallyPass, rallyContinue,
  };
}

// ── Casino auto-chain (solo only — see header deferral note) ─────────────────

function _doCasinoSoloChain(engine: SoloEngine | null, onGridChanged: () => void): void {
  const s = useFarkleStore.getState();
  if (!engine || s.gamePhase !== 'playing') return;

  const grid = engine.grid;
  const table = getTable();
  for (let r = 0; r < grid.length; r++) {
    for (let c = 0; c < grid[r]!.length; c++) {
      const start = grid[r]![c];
      if (!start || !_isChainableCell(start)) continue;
      const found = _findScoringPath(grid, { row: r, col: c }, table);
      if (!found) continue;

      useFarkleStore.getState().clearChain();
      for (const p of found) {
        const cell = grid[p.row]![p.col]!;
        useFarkleStore.getState().addToChain(`${p.row},${p.col}`, _rawFace(cell));
      }

      setTimeout(() => {
        const resolvedFaces = engine.resolveFaces(found);
        useFarkleStore.setState({ chainFaces: resolvedFaces });
        const result = useFarkleStore.getState().commitChain();
        if (result !== 'ok') return;
        engine.refillAfterChain(found, useFarkleStore.getState().catalystBoostPct);
        if (engine.isDeadBoard()) {
          engine.reshuffleFaces();
          if (engine.isDeadBoard()) engine.reshuffleFaces();
        }
        onGridChanged();
      }, 500);
      return; // one chain per interval tick
    }
  }
}

function _findScoringPath(grid: Cell[][], start: GridPos, table: Int32Array): GridPos[] | null {
  const startCell = grid[start.row]![start.col]!;
  const queue: { path: GridPos[]; faces: number[] }[] = [
    { path: [start], faces: [_rawFace(startCell)] },
  ];
  while (queue.length > 0) {
    const { path, faces } = queue.shift()!;
    const resolved = _resolveChainFacesPreview(faces);
    if (lookupScore(resolved as DieFace[], table) > 0) return path;
    if (path.length >= MAX_CHAIN) continue;

    const last = path[path.length - 1]!;
    for (const n of getNeighbors(grid, last.row, last.col)) {
      if (path.some(p => p.row === n.row && p.col === n.col)) continue;
      const nCell = grid[n.row]?.[n.col];
      if (!nCell || !_isChainableCell(nCell)) continue;
      queue.push({ path: [...path, n], faces: [...faces, _rawFace(nCell)] });
    }
  }
  return null;
}

// ── Face resolution helpers ───────────────────────────────────────────────────
// Preview-only (live chainScore display while dragging) — plurality-based,
// does not special-case mirror (mirror positions pass through unresolved,
// matching this preview's pre-existing behavior). The real resolution for
// scoring is SoloEngine.resolveFaces / the server's resolveChainFaces.

function _resolveChainFacesPreview(faces: number[]): number[] {
  return faces.map((f, i) => {
    if (f === 0) {
      const others = faces.filter((_, j) => j !== i && faces[j] !== 0);
      return _plurality(others) ?? 1;
    }
    return f;
  });
}

function _plurality(faces: number[]): number | undefined {
  if (faces.length === 0) return undefined;
  const counts: Record<number, number> = {};
  for (const f of faces) counts[f] = (counts[f] ?? 0) + 1;
  let best: number | undefined; let bestC = 0;
  for (const [f, c] of Object.entries(counts)) {
    if (c > bestC) { bestC = c; best = Number(f); }
  }
  return best;
}

function _randomColumns(count: number): number[] {
  const all = [0, 1, 2, 3, 4, 5, 6];
  for (let i = all.length - 1; i > 0; i--) {
    const j = Math.floor(_sessionRng() * (i + 1));
    [all[i], all[j]] = [all[j]!, all[i]!];
  }
  return all.slice(0, count);
}
