// Auto-generated by: pnpm supabase:gen-types
// Do not edit manually — run `pnpm supabase:gen-types` after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          avatar_url?: string | null
          updated_at?: string
        }
      }
      compliance_flags: {
        Row: {
          user_id: string
          age_verified: boolean
          state_allowed: boolean
          terms_accepted: boolean
          terms_accepted_at: string | null
          restricted_state: string | null
          min_age_required: number
          verified_at: string
        }
        Insert: {
          user_id: string
          age_verified: boolean
          state_allowed: boolean
          terms_accepted: boolean
          terms_accepted_at?: string | null
          restricted_state?: string | null
          min_age_required?: number
          verified_at?: string
        }
        Update: {
          age_verified?: boolean
          state_allowed?: boolean
          terms_accepted?: boolean
          terms_accepted_at?: string | null
        }
      }
      economy_balances: {
        Row: {
          user_id: string
          gold_coins: number
          sweeps_coins: number
          updated_at: string
        }
        Insert: {
          user_id: string
          gold_coins?: number
          sweeps_coins?: number
          updated_at?: string
        }
        Update: {
          gold_coins?: number
          sweeps_coins?: number
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          user_id: string
          type: string
          currency: string
          amount: number
          balance_before: number
          balance_after: number
          metadata: Json
          server_validated: boolean
          blockchain_tx_hash: string | null
          created_at: string
        }
        Insert: {
          id: string
          user_id: string
          type: string
          currency: string
          amount: number
          balance_before: number
          balance_after: number
          metadata?: Json
          server_validated?: boolean
          blockchain_tx_hash?: string | null
          created_at?: string
        }
        Update: {
          blockchain_tx_hash?: string | null
          server_validated?: boolean
        }
      }
      player_saves: {
        Row: {
          user_id: string
          meta_resources: Json
          purchased_upgrade_ids: string[]
          level_progress: Json
          compliance_flags: Json
          ab_assignments: Json
          settings: Json
          updated_at: string
        }
        Insert: {
          user_id: string
          meta_resources?: Json
          purchased_upgrade_ids?: string[]
          level_progress?: Json
          compliance_flags?: Json
          ab_assignments?: Json
          settings?: Json
          updated_at?: string
        }
        Update: {
          meta_resources?: Json
          purchased_upgrade_ids?: string[]
          level_progress?: Json
          compliance_flags?: Json
          ab_assignments?: Json
          settings?: Json
          updated_at?: string
        }
      }
      leaderboard_entries: {
        Row: {
          user_id: string
          level_id: string
          score: number
          updated_at: string
        }
        Insert: {
          user_id: string
          level_id: string
          score: number
          updated_at?: string
        }
        Update: {
          score?: number
          updated_at?: string
        }
      }
      gifts: {
        Row: {
          id: string
          from_user_id: string
          to_user_id: string
          gift_type: string
          amount: number
          claimed: boolean
          created_at: string
          claimed_at: string | null
        }
        Insert: {
          id?: string
          from_user_id: string
          to_user_id: string
          gift_type: string
          amount: number
          claimed?: boolean
          created_at?: string
          claimed_at?: string | null
        }
        Update: {
          claimed?: boolean
          claimed_at?: string | null
        }
      }
      guilds: {
        Row: {
          id: string
          name: string
          description: string | null
          owner_user_id: string
          member_count: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          owner_user_id: string
          member_count?: number
          created_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          member_count?: number
        }
      }
      guild_members: {
        Row: {
          guild_id: string
          user_id: string
          role: 'owner' | 'officer' | 'member'
          weekly_contribution: number
          joined_at: string
        }
        Insert: {
          guild_id: string
          user_id: string
          role?: 'owner' | 'officer' | 'member'
          weekly_contribution?: number
          joined_at?: string
        }
        Update: {
          role?: 'owner' | 'officer' | 'member'
          weekly_contribution?: number
        }
      }
      analytics_events: {
        Row: {
          id: string
          name: string
          props: Json
          user_id: string
          session_id: string
          timestamp: string
          platform: string
          app_version: string
          cohort_id: string | null
        }
        Insert: {
          id?: string
          name: string
          props?: Json
          user_id: string
          session_id: string
          timestamp: string
          platform?: string
          app_version?: string
          cohort_id?: string | null
        }
        Update: never
      }
      blockchain_log: {
        Row: {
          id: string
          user_id: string
          entry_type: string
          payload_hash: string
          tx_hash: string | null
          block_number: number | null
          chain_status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          entry_type: string
          payload_hash: string
          tx_hash?: string | null
          block_number?: number | null
          chain_status?: string
          created_at?: string
        }
        Update: {
          tx_hash?: string | null
          block_number?: number | null
          chain_status?: string
        }
      }
      quest_cache: {
        Row: {
          cache_key: string
          quest_json: Json
          hit_count: number
          generated_at: string
          expires_at: string
        }
        Insert: {
          cache_key: string
          quest_json: Json
          hit_count?: number
          generated_at?: string
          expires_at: string
        }
        Update: {
          quest_json?: Json
          hit_count?: number
          expires_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      get_leaderboard_rank: {
        Args: { p_user_id: string; p_level_id: string }
        Returns: number
      }
    }
    Enums: Record<string, never>
  }
}
